[project]
name = "foxie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.37.0",
    "python-dotenv>=1.1.1",
    "typer[all]>=0.17.4",
]
