import os
import typer
from foxie_cli.core.models import GeneratedCode

def write_files(generated_code: GeneratedCode, base_dir: str = "."):
    """
    Writes the generated code files to the specified base directory.

    Iterates through the CodeFile objects, ensures directories exist,
    and writes the content to each file.
    """
    typer.secho("\n📝 Writing generated files to disk...", fg=typer.colors.BLUE)

    if not generated_code.files:
        typer.secho("Warning: No files were generated by the AI.", fg=typer.colors.YELLOW)
        return

    for code_file in generated_code.files:
        # Construct the full path (e.g., ./app/models/product.py)
        file_path = os.path.join(base_dir, code_file.file_path)
        
        # Get the directory part (e.g., ./app/models)
        directory = os.path.dirname(file_path)

        try:
            # Create the directory if it doesn't exist
            if directory:
                os.makedirs(directory, exist_ok=True)

            # Write the file content
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(code_file.content)
            
            typer.secho(f"  ✅ Created: {file_path}", fg=typer.colors.GREEN)

        except OSError as e:
            typer.secho(f"  ❌ Error creating file {file_path}: {e}", fg=typer.colors.RED)
            raise typer.Exit(code=1)